ignore-paths:
  - build
  - deprecated
  - pddl/parser
  - doc/src

strictness: veryhigh
test-warnings: true
doc-warnings: true
member-warnings: true

pep257:
  disable:
    - D213
    - D211
    - D107
    - D105
