ignore-paths:
  - build

strictness: veryhigh
test-warnings: true
doc-warnings: false
member-warnings: true

pep257:
  disable:
    - D213
    - D211
    - D107
    - D105
pep8:
  disable:
    - E408
